### ISSUE TITLE
Left hand navigation 'My courses' item

### ISSUE THREAD

**Issue by andrea-sch** [navitaslts/moodle-theme_ncmboost#6]
![image](https://user-images.githubusercontent.com/27271204/54099532-e2180780-440d-11e9-9f55-d8b545533023.png)

Can you make the yellow item like it was in the previous version 
![image](https://user-images.githubusercontent.com/27271204/54099557-fbb94f00-440d-11e9-88f4-475485dbfcf5.png)

**Comment by Nicosoft** [comment]
We keep the icon, we increase indent to course action item
